subinclude("//build_defs/sdk")

proto_build_defs(
    name = "go",
    srcs = ["go.build_defs"],
    visibility = ["PUBLIC"],
    proto_languages = {
        "grpc_language": ["go_grpc_language"],
        "proto_language": ["go_proto_language"],
    }
)

proto_build_defs(
    name = "py",
    srcs = ["py.build_defs"],
    visibility = ["PUBLIC"],
    proto_languages = {
        "grpc_language": ["py_grpc_language"],
        "proto_language": ["py_proto_language"],
    }
)

proto_build_defs(
    name = "js",
    srcs = ["js.build_defs"],
    visibility = ["PUBLIC"],
    proto_languages = {
        "grpc_language": ["js_grpc_language"],
        "proto_language": ["js_proto_language"],
    }
)