subinclude("//build_defs:proto")

proto_library(
    name = "proto",
    srcs = [
        "other_test.proto",
        "test.proto",
    ],
    languages = ["go"],
    root_dir = "test",
    visibility = ["//test/root_dir:root_dir_test"],
)
